name: CI

on:
    push:
    pull_request:
        types: [opened, edited, reopened]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo:4.4.6
                env:
                    MONGO_INITDB_ROOT_USERNAME: admin
                    MONGO_INITDB_ROOT_PASSWORD: admin
                    MONGO_INITDB_DATABASE: APP-DATABASE
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd mongo
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            MONGODB_CONNECTION_URI: mongodb://admin:admin@localhost:27017/APP-DATABASE

        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7

            - name: Install dependencies
              run: pnpm install

            - name: Setup database
              run: pnpm prisma db push

            - name: Run tests
              run: pnpm test run

            - name: Check
              run: pnpm run check

            - name: Lint
              run: pnpm lint
